	TITLE	'8080 JUMPS, CALLS, AND RETURNS'
;
;	JUMPS ALL REQUIRE A 16 BIT OPERAND
	JMP	L1		;JUMP UNCONDITIONALLY TO LABEL
	JNZ	L1+'A1'		;JUMP ON NON ZERO TO LABEL
	JZ	100H		;JUMP ON ZERO CONDITION TO LABEL
	JNC	L1+4		;JUMP ON NO CARRY TO LABEL
	JC	'AB'		;JUMP ON CARRY TO LABEL
	JPO	$+8		;JUMP ON PARITY ODD TO LABEL
	JPE	L1/2		;JUMP ON EVEN PARITY TO LABEL
	JP	GAMMA		;JUMP ON POSITIVE RESULT TO LABEL
	JM	LOW L1		;JUMP ON MINUS TO LABEL
L1:

	;CALL OPERATIONS ALL REQUIRE A 16-BIT OPERAND
	CALL	S1		;CALL SUBROUTINE UNCONDITIONALLY
	CNZ	S1+X		;CALL SUBROUTINE IF NON ZERO FLAG
	CZ	100H		;CALL SUBROUTINE IF ZERO FLAG
	CNC	S1+4		;CALL SUBROUTINE IF NO CARRY FLAG
	CC	S1 MOD 3	;CALL SUBROUTINE IF CARRY FLAG
	CPO	$+8		;CALL SUBROUTINE IF PARITY ODD
	CPE	S1-$		;CALL SUBROUTINE IF PARITY EVEN
	CP	GAMMA		;CALL SUBROUTINE IF POSITIVE
	CM	GAM$MA		;CALL SUBROUTINE IF MINUS FLAG
S1:
;
;	PROGRAMMED RESTART (RST) REQUIRES 3-BIT OPERAND
;	(RST X IS EQUIVALENT TO CALL X*8)
	RST	0		;"RESTART" TO LOCATION 0
	RST 	X+1
;
;	RETURN INSTRUCTIONS HAVE NO OPERAND
	RET			;RETURN	FROM SUBROUTINE
	RNZ			;RETURN	IF NON ZERO
	RZ			;RETURN	IF ZERO FLAG SET
	RPO			;RETURN	IF PARITY IS ODD
	RPE			;RETURN	IF PARITY IS EVEN
	RP			;RETURN	IF POSITIVE RESULT
	RM			;RETURN	IF MINUS FLAG SET
;
X	EQU	2
GAMMA:
	END
