TRUE	EQU	0FFFFH		;DEFINE "TRUE"
FALSE	EQU	NOT TRUE	;DEFINE "FALSE"
TTY	EQU	TRUE		;SET TTY ON
TTYBASE	EQU	10H		;BASE OF TTY PORTS
CRTBASE	EQU	20H		;RASE OF CRT PORTS
	IF	TTY		;ASSEMBLE TTY PORTS
	TITLE	'Teletype Echo Program'
CONIN	EQU	TTYBASE		;CONSOLE INPUT
CONOUT	EQU	TTYBASE+1	;CONSOLE OUT
	ENDIF
	IF	NOT TTY		;ASSEMBLE CRT PORTS
	TITLE	'CRT Echo Program'
CONIN	EQU	CRTBASE		;CONSOLE IN
CONOUT	EQU	CRTBASE+1	;CONSOLE OUT
	ENDIF
;
ECHO:	IN	CONIN	;READ CONSOLE CHARACTER
	OUT	CONOUT	;WRITE CONSOLE CHARACTER
	JMP	ECHO
	END
