	TITLE	'Typer Program'
	PAGE	33
;	PRINT THE MESSAGE SELECTED BY THE INPUT COMMAND A,B, OR C
VERS	EQU	10		;VERSION NUMBER N.N
BOOT	EQU	0000H		;REBOOT ENTRY POINT
BDOS	EQU	0005H		;BDOS ENTRY POINT
TFCB	EQU	005CH		;DEFAULT FILE CONTROL BLOCK (GET A,B, OR C)
WCHAR	EQU	2		;WRITE CHARACTER FUNCTION
CR	EQU	0DH		;CARRIAGE RETURN CHARACTER
LF	EQU	0AH		;LINE FEED CHARACTER
STKSIZ	EQU	16		;SIZE OF LOCAL STACK (IN DOUBLE BYTES)
;
	ORG	100H		;ORIGIN AT BASE OF TPA
	JMP	START		;JUMP PAST THE MESSAGE SUBROUTINE
;
WMESSAGE:
	;WRITE THE STRING AT THE ADDRESS GIVEN BY HL UNTIL 00
		MOV A,M! ORA A! RZ 	;RETURN IF AT 00
		MOV E,A! MVI C,WCHAR! PUSH H ;READY TO PRINT
		CALL BDOS! POP H 	;CHARACTER PRINTED, GET NEXT
		INX H! JMP WMESSAGE
;
START:	;ENTER HERE FROM THE CCP, RESET TO LOCAL STACK
	LXI	SP,STACK	;SET TO LOCAL STACK
	LXI	H,SIGNON	;WRITE THE MESSAGE
	CALL	WMESSAGE	;'TYPER' VERSION N.N
;
	LDA	TFCB+l		;GET FIRST CHAR TYPED AFTER NAME
	SUI	'A'		;NORMALIZE TO 0,1,2
	CPI	TABLEN		;COMPARE WITH THE TABLE LENGTH
	JNC	BOOT		;REBOOT IF NOT VALID
;
;	COMPUTE INDEX INTO ADDRESS TABLE BASED ON A'S VALUE
	MOV	E,A		;LOW ORDER INDEX
	MVI	D,0		;EXTENDED TO DOUBLE PRECISION
	LXI	H,TABLE		;BASE OF THE TABLE TO INDEX
	DAD	D		;SINGLE PRECISION INDEX
	DAD	D		;DOUBLE PRECISION INDEX
	MOV	E,M		;LOW ORDER BYTE TO E
	INX	H
	MOV	D,M		;HIGH ORDER MESSAGE ADDRESS TO DE
	XCHG			;READY FOR PRINTOUT
	CALL	WMESSAGE	;MESSAGE WRITTEN To CONSOLE
	JMP	BOOT		;REBOOT, GO BACK TO CCP LEVEL
;
;	DATA AREAS
SIGNON:
	DB	'''typer'' version '
	DB	VERS/10 + '0', '.', VERS MOD 10 + '0'
	DB	CR,LF,0 	;END OF MESSAGE
;
TABLE:	;OF MESSAGE BASE ADDRESSES
	DW	MESS@A,MESS@B,MESS@C
TABLEN	EQU	($-TABLE)/2	;LENGTH OF TABLE
MESS@A:	DB	'this is message a',CR,LF,0
MESS@B:	DB	'you selected b this time',CR,LF,0
MESS@C:	DB	'this message comes out for c',CR,LF,0
;
	DS	STKSIZ*2	;RESERVES AREA FOR STACK
STACK:

