	TITLE	'IMMEDIATE OPERAND INSTRUCTIONS'
;	
;	MVI USES A REGISTER WITH OPERAND AND 8-BIT DATA
	MVI	B,255		;MOVE IMMEDIATE A,B,C,D,E,H,L,M
;
;	ALL REMAINING IMMEDIATE OPERATIONS USE A REGISTER
	ADI	1		;ADD IMMEDIATE TO A W/O CARRY
	ACI	0FFH		;ADD IMMEDIATE TO A WITH CARRY
	SUI	L1+3		;SUBTRACT FROM A W/O BORROW (CARRY)
	SBI	LOW L1		;SUBTRACT FROM A WITH BORROW (CARRY)
	ANI	$ AND 7		;LOGICAL "AND" WITH IMMEDIATE DATA
	XRI	1111$00B	;LOGICAL "XOR" WITH IMMEDIATE DATA
	ORI	-3		;LOGICAL "OR" WITH IMMEDIATE DATA
L1:
	END

