	TITLE	'DATA/MEMORY/REGISTER MOVE OPERATIONS'
;
;	THE MOV INSTRUCTION REQUIRES TWO REGISTER OPERANDS
;	(3-BITS) SELECTED FROM A,B,C,D,E,H, OR M (M,M INVALID)
	MOV	A,B		;MOVE DATA TO FIRST REGISTER FROM SECOND
;
;	LOAD/STORE EXTENDED REQUIRE REGISTER PAIR B OR D
	LDAX	B		;LOAD ACCUM FROM ADDRESS GIVEN BY BC
	STAX	D		;STORE ACCUM TO ADDRESS GIVEN BY DE
;
;	LOAD/STORE DIRECT REQUIRE MEMORY ADDRESS
	LHLD	D1		;LOAD HL DIRECTLY FROM ADDRESS D1
	SHLD	D1+2		;STORE HL DIRECTLY TO ADDRESS D1+2
	LDA	D1		;LOAD THE ACCUMULATOR FROM D1
	STA	D1 SHL 2	;STORE THE ACCUMULATOR TO D1 SHL 2
;
;	PUSH AND POP REQUIRE PSW OR REGISTER PAIR FROM B,D,H
	POP	PSW		;LOAD REGISTER PAIR FROM STACK
	PUSH	B		;STORE REGISTER PAIR TO THE STACK
;
;	INPUT/OUTPUT INSTRUCTIONS REQUIRE 8-BIT PORT NUMBER
	IN	X+2		;READ DATA FROM PORT NUMBER TO A
	OUT	0FEH		;WRITE DATA TO THE SPECIFIED PORT
;
;	MISCELLANEOUS REGISTER MOVE OPERATIONS
	XTHL			;EXCHANGE TOP OF STACK WITH HL
	PCHL			;PC RECEIVES THE HL VALUE
	SPHL			;SP RECEIVES THE HL VALUE
	XCHG			;EXCHANGE DE AND HL
;
;	END OF INSTRUCTION LIST
D1:	DS	2		;DOUBLE WORD TEMPORARY
	DS	2		;ANOTHER TEMPORARY
X	EQU	4		;LITERAL VALUE
	END

