	TITLE	'ARITHMETIC LOGIC UNIT OPERATIONS'
;
;	ASSUME OPERATION WITH ACCUMULATOR AND REGISTER,
;	WHICH MUST PRODUCE A, B, C, D, E, H, L, OR M
;
	ADD	B	;ADD REGISTER TO A W/O CARRY
	ADC	L	;ADD TO A WITH CARRY INCLUDED
	SUB	H	;SUBTRACT FROM A W/O BORROW
	SBB	B+1	;SUBTRACT FROM A WITH BORROW
	ANA	C	;LOGICAL "AND" WITH REGISTER
	XRA	A	;LOGICAL "XOR" WITH REGISTER
	ORA	B	;LOGICAL "OR" WITH REGISTER
	CMP	H	;COMPARE REGISTER, SETS FLAGS
;
;	DOUBLE ADD CHANGES HL PAIR ONLY
	DAD	B	;DOUBLE ADD B,D,H,SP TO HL
;
;	REMAINING OPERATIONS HAVE NO OPERANDS
	DAA	;DECIMAL ADJUST REGISTER A USING LAST OP
	CMA	;COMPLEMENT THE BITS OF THE A REGISTER
	STC	;SET THE CARRY FLAG TO I
	CMC	;COMPLEMENT THE CARRY FLAG
	RLC	;8-BIT ACCUM ROTATE LEFT, AFFECTS CY
	RRC	;8-BIT ACCUM ROTATE RIGHT, AFFECTS CY
	RAL	;9-BIT CY/ACCUM ROTATE LEFT
	RAR	;9-BIT CY/ACCUM ROTATE RIGHT
;
	END
