	TITLE	'INCREMENT AND DECREMENT INSTRUCTIONS'
;
;	INSTRUCTIONS REQUIRE REGISTER (3-BIT) OPERAND
	INR	E		;BYTE INCREMENT A,B,C,D,E,H,L,M
	DCR	A		;BYTE DECREMENT A,B,C,D,E,H,L,M
	INX	SP		;16-BIT INCREMENT B,D,H,SP
	DCX	B		;16-BIT DECREMENT B,D,H,SP
	END
