;	SAMPLE USE OF THE EXITM STATEMENT WITH THE IRPC MACRO
;
;	THE FOLLOWING IRPC FILLS AN AREA OF MEMORY WITH AT MOST
;	EIGHT BYTES OF DATA:
LEN	SET	0	;INITIALIZE LENGTH TO 0
	IRPC	N,SHORT
	DB	'&N'
LEN	SET	LEN+1
	IF	LEN = 8
	EXITM		;STOP MACRO IF AREA IS FULL
	ENDIF
	ENDM
;
;	THE FOLLOWING MACRO PERFORAMS EXACTLY THE SAME FUNCTIONS AS
;	SHOWN ABOVE, BUT ABORTS EXPANSION WHEN LENGTH EXCEEDS 8
;
LEN	SET	0	;INITIALIZE LENGTH COUNTER
	IRPC	N,LONGSTRING
	DB	'&N'
LEN	SET	LEN+1
	IF	LEN EQ 8
	EXITM
	ENDM
	END
