	ORG	100H	;BASE OF THE TPA
BDOS	EQU	5	;BDOS ENTRY POINT
PMSG	EQU	9	;PRINT 'TIL $ FUNCTION
CR	EQU	0DH	;CARRIAGE RETURN
LF	EQU	0AH	;LINE FEED
;
PRINT	MACRO N,MESSAGE
;;	PRINT MESSAGE, FOLLOWED BY N CRLF'S
	LOCAL	PASTM,MSG
	JMP	PASTM	;;JUMP PAST MSG
MSG:	DB	MESSAGE	;;INCLUDE TEXT TO WRITE
	REPT	N	;;REPEAT CR LF SEQUENCE
	DB	CR,LF
	ENDM
	DB	'$'	;;MESSAGE TERMINATOR
PASTM:	LXI	D,MSG	;;MESSAGE ADDRESS
	MVI	C,PMSG	;;PRINT FUNCTION
	CALL	BDOS
	ENDM
;
	PRINT	2,'The rain in Spain goes'
	PRINT	0,'mainly down the drain.'
	RET
	END
