	ORG	100H	;BASE OF TRANSIENT AREA
BDOS	EQU	5	;BDOS ENTRY POINT
CONOUT	EQU	2	;CHARACTER OUT FUNCTION
;
SAVE	MACRO		;SAVE ALL CPU REGISTERS
	PUSH	PSW
	PUSH	B
	PUSH	D
	PUSH	H
	ENDM
;
RESTORE	MACRO		;RESTORE ALL REGISTERS
	POP	H
	POP	D
	POP	B
	POP	PSW
	ENDM
;
WCHAR	MACRO	CHR	;WRITE CHR TO CONSOLE
	MVI	C,CONOUT	;;CHAR OUT FUNCTION
	MVI	E,'&CHR'	;;CHAR TO SEND
	CALL	BDOS
	ENDM
;
;	MAIN PROGRAM STARTS HERE
	SAVE		;SAVE REGISTERS UPON ENTRY
	WCHAR	H	;SEND 'H' TO CONSOLE
	WCHAR	I	;SEND 'I' TO CONSOLE
	RESTORE		;RESTORE CPU REGISTERS
	RET		;RETURN TO CCP
	END
