	ORG	100H		;BASE OF THE TRANSIENT AREA
BDOS	EQU	5		;BDOS ENTRY POINT
CR	EQU	0DH		;CARRIAGE RETURN (ASCII)
LF	EQU	0AH		;LINE FEED (ASCII)
;
;	SAMPLE PROGRAM SHOWING THE USE OF 'LOCAL'
;
	REPT	4		;REPEAT GENERATION 4 TIMES
	LOCAL	X,Y		;;GENERATE TWO LABELS
	JMP	Y		;JUMP PAST THE MESSAGE
X:	DB	'print x=&X, y=&Y',CR,LF,'$'
Y:	LXI	D,X		;READY PRINT STRING
	CALL	PRINT
	ENDM
	RET
;
PRINT:	MVI	C,9
	CALL	BDOS
	RET
	END
