	ORG	100H	;BASE OF TRANSIENT AREA
	TITLE	'SAMPLE REPT STATEMENT'
;	THIS PROGRAM READS INPUT PORT 0 AND INDEXES INTO A TABLE
;	BASED ON THIS VALUE. THE TABLE VALUE IS FETCHED AND SENT
;	TO OUTPUT PORT 0
;
MAXVAL EQU	5	;LARGEST VALUE TO PROCESS
RLOOP:	IN	0	;READ THE PORT VALUE
	CPI	MAXVAL	;TOO LARGE?
	JNC	RLOOP	;IGNORE INPUT IF INVALID
	LXI	H,TABLE	;ADDRESS BASE OF TABLE
	MOV	E,A	;LOW ORDER INDEX TO E
	MVI	D,0	;HIGH ORDER 00 FOR INDEX
	DAD	D	;HL HAS ADDRESS OF ELEMENT
	MOV	A,M	;FETCH TABLE VALUE FOR OUTPUT
	OUT	0	;SEND TO THE OUTPUT PORT AND LOOP
	JMP	RLOOP	;FOR ANOTHER INPUT
;
;	GENERATE A TABLE OF VALUES MAXVAL,MAXVAL-1,...,1
NXTVAL	SET	MAXVAL	;START COUNTER AT MAXVAL
TABLE:	REPT	NXTVAL
	DB	NXTVAL ;FILL ONE (MORE) ELEMENT
NXTVAL	SET	NXTVAL-1;;AND DECREMENT FILL VALUE
	ENDM
	END
