	TITLE 'SAMPLE MESSAGE OUTPUT MACRO'
;
;
	MACLIB MSGLIB	;INCLUDE THE MACRO LIBRARY
	ORG TPA	;ORIGIN AT THE TRANSIENT AREA
;   USE THE MACRO LIBRARY TO TYPE TWO MESSAGES
	ENTCCP	10	;ENTER PROGRAM, RESERVE 10 LEVEL STACK
	TYPEOUT <THIS IS THE FIRST MESSAGE>
	TYPEOUT	<THIS IS THE SECOND MESSAGE>
	TYPEOUT	<THIS IS THE THIRD MESSAGE>
	RETCCP		;RETURN TO THE CONSOLE COMMAND PROCESSOR
	END
