	ORG	100H	;BASE OF THE TPA
FALSE	EQU	0000H	;VALUE OF FALSE
TRUE	EQU	NOT FALSE;VALUE OF TRUE
;	LISTDEV IS TRUE IF LIST DEVICE IS USED
;	FOR OUTPUT, AND FALSE IF CONSOLE IS USED
LISTDEV	EQU	TRUE
;
;
BDOS	EQU	5	;BDOS ENTRY POINT
CONOUT	EQU	2	;WRITE TO CONSOLE
LISTOUT	EQU	5	;WRITE TO LIST DEVICE
;
SETIO	MACRO	;SETUP "OUTPUT" MACRO FOR LIST OR CONSOLE
;
OUTPUT	MACRO	CHAR
	MVI	E,CHAR	;;READY THE CHARACTER FOR PRINTING
	IF	LISTDEV
	MVI	C,LISTOUT
	ELSE
	MVI	C,CONOUT
	ENDIF
	CALL	BDOS
	ENDM
	OUTPUT	'*'
	ENDM
;
	SETIO		;SETUP THE I0 SYSTEM
	OUTPUT	'1'
	OUTPUT	'2'
	RET
	END
