	ORG	100H		;BASE OF TPA
MOVE	MACRO	SOURCE,DEST,COUNT
;;	MOVE DATA FROM ADDRESS GIVEN BY 'SOURCE'
;;	TO ADDRESS GIVEN BY 'DEST' FOR 'COUNT' BYTES
	LOCAL	PASTSUB ;;LABEL AT END OF SUBROUTINE
;;
	JMP	PASTSUB ;;JUMP AROUND INLINE SUBROUTINE
@MOVE:	;;INLINE SUBROUTINE TO PERFORM MOVE OPERATION
;;	HL IS SOURCE, DE IS DEST, BC IS COUNT
	MOV	A,C	;;LOW ORDER COUNT
	ORA	B	;;ZERO COUNT?
	RZ		;;STOP MOVE IF ZERO REMAINDER
	MOV	A,M	;;GET NEXT SOURCE CHARACTER
	STAX	D	;;PUT NEXT DEST CHARACTER
	INX	H	;;ADDRESS FOLLOWING SOURCE
	INX	D	;;ADDRESS FOLLOWING DEST
	DCX	B	;;COUNT=COUNT-1
	JMP	@MOVE	;;FOR ANOTHER BYTE TO MOVE
PASTSUB:
;;	ARRIVE HERE ON FIRST INVOCATION - REDEFINE MOVE
MOVE	MACRO	?S,?D,?C	;;CHANGE PARM NAMES
	LXI	H,?S	;;ADDRESS THE SOURCE STRING
	LXI	D,?D	;;ADDRESS THE DEST STRING
	LXI	B,?C	;;PREPARE THE COUNT
	CALL	@MOVE	;;MOVE THE STRING
	ENDM
;;	CONTINUE HERE ON THE FIRST INVOCATION TO USE
;;	THE REDEFINED MACRO TO PERFORM THE FIRST MOVE
	MOVE	SOURCE,DEST,COUNT
	ENDM
;
	MOVE	X1,X2,5 ;MOVE 5 CHARS FROM X1 TO X2
	MOVE	3000H,1000H,1500H	;BIG MOVER
	RET			;RETURN TO THE CCP
X1:	DB	'here is some data to move'
X2:	DB	'xxxxxwe are!'
	END

