
	ORG	100H	;BASE OF TRANSIENT AREA
;	SAMPLE PROGRAM SHOWING RECURSIVE MACROS
BDOS	EQU	0005H	;ENTRY TO BDOS
CONOUT	EQU	2	;CONSOLE CHARACTER OUT
MSGOUT	EQU	9	;PRINT MESSAGE 'TIL $
CR	EQU	0DH	;CARRIAGE RETURN
LF	EQU	0AH	;LINE FEED
;
WCHAR	MACRO	CHR
;;	WRITE THE CHARACTER CHR TO CONSOLE
	CBDOS	CONOUT,CHR	;;CALL BDOS
	ENDM
;
CBDOS	MACRO	FUNC,INFO
;;	GENERAL PURPOSE BDOS CALL MACRO
;;	FUNC IS THE FUNCTION NUMBER,
;;	INFO IS THE INFORMATION ADDRESS OR NUL
;;	CHECK FOR FUNCTION 9, SEND CRLF FIRST IF SO
	IF	FUNC=MSGOUT
;;	PRINT CRLF FIRST
	WCHAR	CR
	WCHAR	LF
	ENDIF
;;	NOW PERFORM THE FUNCTION
	MVI	C,FUNC
;;	INCLUDE LXI TO DE IF INFO NOT EMPTY
	IF	NOT NUL INFO
	LXI	D,INFO
	ENDIF
	CALL	BDOS
	ENDM
;
	WCHAR	'h'	;SEND "H" TO CONSOLE
	WCHAR	'i'	;SEND "I" TO CONSOLE
	CBDOS	MSGOUT,MSGADDR ;SEND MESSAGE
	RET		;TERMINATE PROGRAM
MSGADDR:
	DB	' and lois$'
	END
