;	INTERSECTION: BUMPENRAM BLVD / LULLABYE LN.

CWCNT	EQU	4		;SET TO 4 CROSSWALK SWITCHES
LULL0	EQU	0		;NAME FOR TREADLE ZERO
LULL1	EQU	1		;NAME FOR TREADLE ONE

	MACLIB	INTER		;BASIC INTERSECTION
	MACLIB TREADLES		;INCLUDE TREADLES
	MACLIB BUTTONS		;INCLUDE PUSHBUTTONS

CYCLE:	;ENTER HERE ON EACH MAJOR CYCLE OF THE LIGHT
	CLOCK? 2,5,NIGHT	;SPECIAL FLASHING?
	;NOT BETWEEN 2 AND 5 AM
	SETLITE NS,RED		;RED LIGHT ON LULLABYE
	SETLITE EW,GREEN	;GREEN ON BUMPENRAM

SAMPLE:	;SAMPLE THE BUTTONS AND TREADLES
	PUSH?	SWITCH		;ANYONE THERE?
	TREAD?	LULL0,SWITCH	;TREADLE 0?
	TREAD?	LULL1,SWITCH	;TREADLE 1?
	CLOCK?	2,,NIGHT	;PAST 2 AM?
	RETRY	SAMPLE	;TRY AGAIN IF NOT

SWITCH:
	;SOMEONE IS WAITING, CHANGE LIGHTS
	SETLITE	EW,YELLOW	;SLOW 'EM DOWN
	TIMER	3		;WAIT 3 SECONDS
	SETLITE	EW,RED		;STOP 'EM
	SETLITE	NS,GREEN	;LET 'EM GO
	TIMER	23		;FOR AWHILE

DONE?:	;IS ALL THE TRAFFIC THROUGH ON LULLABYE?
	TREAD?	LULL0,NOTDONE	;TREADLE 0?
	TREAD?	LULL1,NOTDONE	;TREADLE 1?
	;NEITHER TREADLE IS SET, CYCLE
	RETRY	CYCLE	;FOR ANOTHER LOOP

NOTDONE:
	TIMER	5	;WAIT 5 SECONDS
	RETRY	DONE?	;TRY AGAIN

NIGHT:	;THIS IS NIGHTTIME, FLASH LIGHTS
	SETLITE	EW,OFF	;TURN OFF
	SETLITE	NS,OFF	;TURN OFF
	TIMER	1	;WAIT WITH OFF
	SETLITE	EW,YELLOW	;TURN TO YELLOW
	SETLITE	NS,RED	;TURN TO RED
	TIMER	1	;LEAVE ON FOR 1 SEC
	RETRY	CYCLE	;GO AROUND AGAIN
	END
