;	AVERAGING PROGRAM WITH INTERSPERSED DEBUG CODE
;
	MACLIB	DSTACK	;READ THE STACK MACHINE OPCODES
	SIZ	20	;CREATE 20 LEVEL WORKING STACK
	TRT	T	;MACHINE CODE TRACE ON
	TRT	P	;PRINT TRACE ON
	PRN	<TRACE FOR AVERAGING PROGRAM>
LOOP:	RDM	0	;READ A-D PORT 0
	DMP		;WRITE TOP OF STACK
	RDM	1	;READ A-D PORT 1
	DMP		;WRITE TOP OF STACK
	RDM	2	;READ A-D PORT 2
	DMP		;WRITE TOP OF STACK
	RDM	3	;READ A-D PORT 3
	DMP		;WRITE TOP OF STACK
	PRN	<FOUR VALUES HAVE BEEN READ>

;	ALL FOUR VALUES ARE STACKED, ADD THEM UP
	SUM		;AD3+AD2
	DMP		;WRITE FIRST SUM
	SUM		;(AD3+AD2)+AD1
	DMP		;WRITE SECOND SUM
	SUM		;((AD3+AD2)+AD1)+ADO
	PRN	<VALUES	HAVE BEEN ADDED>
	DMP		;WRITE SUM OF VALUES

;	SUM IS AT TOP OF THE STACK, DIVIDE BY 4
	LSR	2	;SHIFT RIGHT TWO = DIV BY 4
	PRN	<AVERAGE VALUE CALCULATED>
	DMP		;WRITE AVERAGE VALUE
	WRM	0	;WRITE RESULT TO D-A PORT 0
	BRN	LOOP	;GO GET ANOTHER SET OF VALUES
	XIT		;EMIT EXIT CODE
