	MACLIB	DSTACK	;STACK MACHINE SIMULATION
	SIZ	50	;50 LEVEL STACK
	TRT	P	;TURN ON PRN TRACE
	TRT	T	;TURN ON CODE TRACE
	PRN	<COMPUTATION OF TOOL TRAVEL DISTANCE>
	LIT	0	;INITIALIZE INDEX
	STO	I	;I=0
	TRF	T	;TURN CODE TRACE OFF
;   LOOK FOR STATING MOTION (NON ZERO VALUE)
MOVE?:  ;READ A-D CONVERTER FOR NON ZERO
	RDM	0
	STO	X	;HOLD TEMPORARILY
	VAL	X	;RELOAD FOR TEST
	LIT	1	;X GEQ 1 TEST
	GEQ	READ	;X GEQ 1?
	BRN	MOVE?	;RETRY IF NOT

READ:
	PRN	<STORE FIRST/NEXT VALUE>
	DMP	X
	VAL	X	;LOAD FIRST/NEXT VALUE
	STO	V,I	;STORE TO THE ITH ELEMENT
	VAL	I	;INCEMENT 1
	LIT	1
	SUM		;I+1
	STO	I	;I=I+1
	GEQ	COMP	;COMPUTE DISTANCE IF 0
	RDM	0	;READ ANOTHER DATA ITEM
	STO	X	;SAVE IT IN X
	BRN	READ	;TO STORE AND TEST

COMP:	PRN	<VALUE ARE LOADED>
	DMP	V,10
;	NOW COMPUTE DISTANCE TRAVELLED BY TOOL
	LIT	0
	DUP		;TWO ZEROS
	STO	I	;I=0
	STO	TOTAL	;TOTAL=0
GETNXT:	PRN	<COMPUTING NEXT INTERVAL>
	DMP	I
	DMP	TOTAL
	DMP	<V,I>,2
	LIT	0	;ZERO AT END
	VAL	V,I	;AT END?
	GEQ	ENDF	;0 GEQ X(I)?

;	NOT AT END OF INVERVAL, COMPUTE NEXT TRAPEZOID
	VAL	V,I
	VAL	V,I,1	;V(I),V(I+1)
	SUM		;V(I)+V(I+1)
	LSR	1	;(V(I)+V(I+1))/2
	VAL	TOTAL	;READY TOTAL
	SUM		;TOTAL=TOTAL+TRAPEZOID
	STO	TOTAL	;BACK TO SUM

	VAL	I	;I=I+1
	LIT	1
	SUM
	STO	I	;BACK TO I
	BRN	GETNXT

ENDF:	PRN	<END OF COMPUTATION>
	DMP	TOTAL
	VAL	TOTAL	;LOAD FOR D-A OUTPUT
	WRM	0	;WRITE D-A PORT
	XIT
;
;	DATA AREA
	DCL	I	;INDEX
	DCL	X	;TEMPORARY
	DCL	V,100	;VELOCITY VECTOR
	DCL	TOTAL	;TOTAL DISTANCE
	END

