;	AVERAGE THE VALUES WHICH ARE READ FROM ANALOG
;	INPUT PORTS, WRITE THE RESULTING VALUE TO ALL
;	THE D-A OUTPUT PORTS.
;
	MACLIB	STACK	;READ THE STACK MACHINE OPCODES
	SIZ	20	;CREATE 20 LEVEL WORKING STACK
LOOP:	RDM	0	;READ A-D PORT 0
	RDM	1	;READ A-D PORT 1
	RDM	2	;READ A-D PORT 2
	RDM	3	;READ A-D PORT 3

;	ALL FOUR VALUES ARE STACKED, ADD THEM UP
	SUM		;AD3+AD2
	SUM		;(AD3+AD2)+ADI
	SUM		;((AD3+AD2)+ADI)+AD0

;	SUM IS AT TOP OF THE STACK, DIVIDE BY 4
	LSR	2	;SHIFT RIGHT TWO = DIV BY 4
	WRM	0	;WRITE RESULT TO D-A PORT 0
	JMP	LOOP	;GO GET ANOTHER SET OF VALUES
