	ORG		100H	;READY FOR THE DEBUG RUN
	MACLIB	INTER	;BASIC MACRO LIBRARY
DEBUG	SET	TRUE	;READY DEBUG TOGGLE
CYCLE:	SETLITE	NS,RED
	SETLITE	EW,GREEN
	TIMER	10
	SETLITE	EW,YELLOW
	TIMER	2
	SETLITE	EW,RED
	SETLITE	NS,GREEN
	TIMER	10
	SETLITE	NS,YELLOW
	TIMER	2
	RETRY 	CYCLE
	END
