	ORG	100H
	MACLIB	SIMPIO	;SIMPLE I/O LIBRARY
	MACLIB	NCOMPARE;EXPANDED COMPARE OPS
	MACLIB	WHEN	;WHEN CONSTRUCT
CYCLE:	WRITE	<TYPE A CHARACTER FROM A TO D >
	READ	X
;	TEST FOR LOWER CASE ALPHABETIC
	WHEN	X,GEQ,61H
	LDA	X
	ANI	5FH	;CLEAR LOWER CASE BIT
	STA	X	;STORE BACK TO X
	ENDW
;	NOW CHECK CASES
;
	WHEN	X,EQL,%'A'
	WRITE	<YOU TYPED AN A>
	JMP	CYCLE
	ENDW
	WHEN	X,EQL,%'B'
	WRITE	<YOU TYPED A B>
	JMP	CYCLE
	ENDW
	WHEN	X,EQL,%'C'
	WRITE	<YOU TYPED A C>
	JMP	CYCLE
	ENDW
	WHEN	X,EQL,%'D'
	WRITE	<YOU TYPED A D>
	WRITE	<BYE^!>
	RET
	ENDW
	WRITE	<NOT AN A, B, C, OR D>
	JMP	CYCLE
X:	DS	1	;TEMP FOR CHARACTER

