	ORG	100H
	MACLIB	SIMPIO	;SIMPLE 10 LIBRARY
	MACLIB	NCOMPARE;EXPANDED COMPARE OPS
	MACLIB	WHEN	;WHEN CONSTRUCT
	MACLIB	DOWHILE ;DOWHILE STATEMENT
	WRITE	<TYPE THE STOP CHARACTER: >
	READ	STOP
;	X = 0 FOR THE FIRST LOOP

	DOWHILE X,NEQ,STOP	;LOOK FOR STOP CHARACTER
	WRITE	<TYPE A CHARACTER: >
	READ	X
	WHEN	X,EQL,%'A'
	WRITE	<YOU TYPED AN A>
	ENDW
;
	WHEN	X,NEQ,%'A'
	WRITE	<NOT AN A>
		WHEN	X,EQL,STOP
		WRITE	<STOP CHARACTER>
		WRITE	<BYE^I>
		ENDW
	ENDW
	ENDDO
;
;	CLEAR THE SCREEN (23 CRLF'S)
	XRA	A
	STA	X	;X=O
	DOWHILE X,LSS,23
	WRITE	<>
	LXI	H,X
	INR	M	;X=X+l
	ENDDO
	RET
;
X:	DB	0	;EXECUTES "DOWHILE" FIRST TIME
STOP:	DS	1	;STOP CHARACTER

