	ORG	100H
	MACLIB	SIMPIO 		;SIMPLE 10 LIBRARY
	MACLIB	COMPARE 	;COMPARISON OPERATORS
;
CYCLE:	WRITE	<TYPE A CHARACTER FROM A TO D >
	READ	X
;	TEST FOR LOWER CASE ALPHABETIC
	LSS	X,61H,NOTRAN
;	ARRIVE HERE IF X IS GREATER OR EQUAL TO
;	A LOWER CASE A (=61H), TRANSLATE
	LDA 	X
	ANI	5FH		;CLEAR LOWER CASE BIT
	STA	X		;STORE BACK TO X
NOTRAN:
;	NOW CHECK CASES
;
	NEQ	X,%'A',NOTA
	WRITE	<YOU TYPED AN A>
	JMP	CYCLE
NOTA:	NEQ	X,%'B',NOTB
	WRITE	<YOU TYPED A B>
	JMP	CYCLE
NOTB:	NEQ	X,%'C',NOTC
	WRITE	<YOU TYPED A C>
	JMP	CYCLE
NOTC:	NEQ	X,%'D',ERROR
	WRITE	<YOU TYPED A D>
	WRITE	<BYE^!>
	RET
ERROR:	WRITE	<NOT AN A, B, C, OR D>
	JMP	CYCLE
X:	DS	1	;TEMP FOR CHARACTER
	END

