	ORG	100H
	MACLIB	SIMPIO ;SIMPLE 10 LIBRARY
	MACLIB	NCOMPARE;COMPARISON OPERATORS
CYCLE:	WRITE	<TYPE A CHARACTER FROM A TO D >
	READ	X
;	TEST FOR LOWER CASE ALPHABETIC
	GEQ	X,%'a',,NOTRAN	;BRANCH ON FALSE
;	X IS GREATER OR EQUAL TO LOWER CASE A
		GTR	X,%'z',NOTRAN
		LDA	X
		ANI	5FH	;UPPER CASE
		STA	X	;BACK TO X
;
NOTRAN:
;	NOW CHECK CASES
;
	NEQ	X,%'A',NOTA
	WRITE	<YOU TYPED AN A>
	JMP	CYCLE
;
	NOTA:	NEQ	X,%'B',NOTB
	WRITE	<YOU TYPED A B>
	JMP	CYCLE
;
NOTB:	NEQ	X,%'C',NOTC
	WRITE	<YOU TYPED A C>
	JMP	CYCLE
;
NOTC:	NEQ	X,%'D',ERROR
	WRITE	<YOU TYPED A D>
	WRITE	<BYE^!>
	RET
ERROR:	WRITE	<NOT AN A, B, C, OR D>
	JMP	CYCLE
X:	DS	1	;TEMP FOR CHARACTER
	END
