	ORG	100H
;	COPY FILE 1 TO FILE 2, CONVERT
;	TO UPPER CASE DURING THE COPY
;	AND ECHO TRANSACTION TO CONSOLE
	MACLIB	SEQIO	;SEQUENTIAL I/O LIB
BOOT	EQU	0000H	;SYSTEM REBOOT
UCASE 	EQU	5FH	;UPPER CASE BITS
;
	LXI 	SP,STACK
;	DEFINE SOURCE FILE:
;		INFILE	=	INPUT FILE
;		SOURCE	=	INTERNAL NAME
;		(NUL)	=	DEFAULT DISK
;		1	=	FIRST DEFAULT NAME
;		(NUL)	=	FIRST DEFAULT TYPE
;		2000 =		BUFFER SIZE
	FILE	INFILE,SOURCE,,1,,2000
;
;	DEFINE DESTINATION FILE:
;		OUTFILE = 	OUTPUT FILE
;		DEST	=	INTERNAL NAME
;		(NUL)	=	DEFAULT DISK
;		2	=	SECOND DEFAULT NAME
;		(NUL)	=	SECOND DEFAULT TYPE
;		2000	=	BUFFER	SIZE
	FILE	OUTFILE,DEST,,2,,2000
;
;	READ SOURCE FILE, TRANSLATE, WRITE DEST
CYCLE:	GET	SOURCE
	CPI	EOF	;END OF FILE?
	JZ	ENDCOPY	;SKIP TO END IF SO
;
;	NOT END OF FILE, CONVERT TO UPPER CASE
	CPI	'a'	;BELOW LOWER CASE "A"?
	JC	NOCONV	;SKIP IF SO
	CPI	'z'+1	;BELOW LOWER CASE "Z"?
	JNC	NOCONV	;SKIP IF ABOVE
;	MASK OUT LOWER CASE ALPHA BITS
	ANI	UCASE
NOCONV:	PUT	CON	;WRITE TO CONSOLE
	PUT	DEST	;AND TO	DESTINATION FILE
	JMP	CYCLE	;FOR ANOTHER CHARACTER
ENDCOPY:
	FINIS	DEST	;END OF OUTPUT
	JMP	BOOT	;BACK TO CCP
	DS	32	;16 LEVEL STACK
STACK:
BUFFERS:
MEMSIZE	EQU	BUFFERS+@NXTB	;PROGRAM SIZE
	END
