	ORG	100H
;	FILE MERGE PROGRAM
	MACLIB	SEQIO		;SEQUENTIAL FILE 1/0
;
BOOT	EQU	0000H		;SYSTEM REBOOT
SEQSIZ	EQU	6		;SIZE OF THE SEQUENCE #'S
USIZE	EQU	1000		;UPDATE BUFFER SIZE
MSIZE	EQU	USIZE		;MASTER BUFFER SIZE
NSIZE	EQU	USIZE+MSIZE	;NEW BUFF SIZE
	LXI	SP,STACK
	JMP	START		;TO PERFORM THE MERGE
;
;	UTILITY SUBROUTINES
;
DIGIT:	;TEST ACCUMULATOR FOR VALID DIGIT
;	RETURN WITH CARRY SET IF INVALID
	CPI	'0'
	RC			;CARRY IF BELOW 0
	CPI	'9'+1		;CARRY IF BELOW 10
	CMC			;NO CARRY IF BELOW 10
	RET
;
;	ERROR MESSAGES FOR READU AND READM
SEQERRU:
	DB	' update seq error',0
SEQERRM:
	DB	' master seq error',0
;
;	GENERATE READU AND READM SUBROUTINES
	IRPC	?F,UM
;	INLINE SEQUENCE NUMBER BUFFER
?F&SEQ:	DB	0		;TO START PROCESSING
	DS	SEQSIZ-1	;REMAINING SPACE FOR SEQ#

READ&?F:
	LXI	H,?F&SEQ	;SEQUENCE BUFFER
	MOV	A,M		;IS IT FF (END FILE)?
	INR	A		;FF BECOMES 00
	RZ			;SKIP THE READ
;
;	READ THE SEQUENCE NUMBER PORTION
	MVI	C,SEQSIZ	;SIZE OF SEQUENCE #
RD&?F&O:
	PUSH	H		;SAVE NEXT TO FILL
	PUSH	B		;SAVE NUMBER COUNT
	GET	?F&FILE		;READ THE FILE
	POP	B		;RECALL COUNT
	POP	H		;RECALL NEXT FILL
	CPI	EOF		;END FILE?
	JZ	EOF&?F
	CALL	DIGIT		;ASCII DIGIT?
	LXI	D,SEQERR&?F	;ERROR MESSAGE
	JC	SEQERR		;SEQUENCE ERROR
;	NO SEQUENCE ERROR, FILL NEXT DIGIT POSITION
	MOV	M,A
	INX	H		;NEXT TO FILL
	DCR	C		;COUNT=COUNT-1
	JNZ	RD&?F&O		;FOR ANOTHER DIGIT
	RET			;END OF FILL

EOF&?F:		;END OF FILE, SET SEQ# TO OFFH
	MVI	A,0FFH
	STA	?F&SEQ		;SEQ# SET TO FF
	RET
	ENDM
;
SEQERR:
;	WRITE ERROR MESSAGE FROM (DE) TIL 00
	LDAX	D
	ORA	A
	JZ	BOOT
;	OTHERWISE, MORE TO PRINT
	PUSH	D
	CON		;WRITE TO CONSOLE
	POP	D
	INX	D
	JMP	SEQERR	;FOR MORE CHARS
;
WRITESEQ:
;	WRITE THE SEQUENCE NUMBER GIVEN BY HL
;	TO THE NEW FILE
	MVI	C,SEQSIZ	;SIZE OF SEQ#
WRIT0:	MOV	A,M
	INX	H		;NEXT TO GET
	PUSH	H		;SAVE NEXT ADDR
	PUSH	B		;SAVE COUNT
	NEW		;WRITE TO NEW
	POP	B		;RECALL COUNT
	POP	H		;RECALL ADDRESS
	DCR	C		;COUNT=COUNT-1
	JNZ	WRIT0		;FOR ANOTHER CHAR
	RET
;
;	COMPARE THE UPDATE SEQUENCE NUMBER WITH
;	THE MASTER SEQUENCE NUMBER, SET:
;		CARRY IF UPDATE < MASTER
;		ZERO IF UPDATE = MASTER
;		-ZERO IF UPDATE > MASTER
COMPARE:
	LXI	D,USEQ	;UPDATE SEQ#
	LXI	H,MSEQ	;MASTER SEQ#
	MVI	C,SEQSIZ	;SEQUENCE SIZE
CLOOP:	LDAX	D	;UPDATE DIGIT
	CMP	M	;UPDATE-MASTER
	RC		;CARRY IF LESS
	RNZ		;NZERO IF GTR
;ITEMS ARE THE SAME, CHECK FOR 0FFH
	CPI	0FFH	;END OF FILE
	RZ		;BOTH ARE 0FFH
	INX	D	;NEXT UPDATE
	INX	H	;NEXT MASTER
	DCR	C	;COUNT DOWN
	JNZ	CLOOP	;FOR ANOTHER DIGIT
	RET		;ZERO FLAG IF EQUAL
;
;	MAIN PROGRAM STARTS HERE
START:
;	UPDATE	FILE, WITH ASSUMED UPD TYPE
	FILE	INFILE,UFILE,,l,UPD,USIZE
;	MASTER	FILE, WITH ASSUMED TYPE MAS
	FILE	INFILE,MFILE,,l,MAS,MSIZE
;	NEW FILE, TEMP.$$$ (RENAMED UPON EOF'S)
	FILE	OUTFILE,NEW,,TEMP,$$$,NSIZE
	CALL	READU	;INITIALIZE UPDATE RECORD
	CALL	READM	;INITIALIZE MASTER RECORD
MERGE:		;MAIN MERGING LOOP
	CALL	COMPARE ;CARRY SET IF UPDATE<MASTER
	JZ	SAME	;ZERO IF IDENTICAL SEQ#
	JNC	MASLOW	;MASTER LOW?
;	UPDATE SEQUENCE NUMBER IS LOW
	LXI	H,USEQ	;COPY SEQUENCE NUMBER
	CALL	WRITESEQ;WRITE THE SEQUENCE #
;
ULOOP:	;UPDATE RECORD TO NEW FILE
	GET	UFILE	;CHARACTER TO A
	PUSH	PSW	;SAVE IT
	PUT	NEW	;OUTPUT TO NEW FILE
	POP	PSW	;RECALL CHARACTER
	CPI	LF	;LINE FEED?
	JZ	ENDUP
	CPI	EOF
	JZ	ENDUP
	JMP	ULOOP	;CYCLE IF NOT END REC
ENDUP:	CALL	READU	;READ ANOTHER SEQ#
	JMP 	MERGE	;FOR ANOTHER RECORD
;
SAME:			;SEQUENCE NUMBERS ARE IDENTICAL
	LDA	MSEQ	;CHECK FOR 0FFH
	CPI	0FFH
	JZ	ENDMERGE
;	NOT THE SAME, DELETE MASTER RECORD
DELMAS:	GET	MFILE
	CPI	EOF	;END OF FILE?
	JZ	GETMAS	;GET SEQ# FF
	CPI	LF
	JNZ	DELMAS	;FOR ANOTHER CHAR
GETMAS:	CALL	READM	;TO NEXT RECORD
	JMP	MERGE	;FOR ANOTHER
;
MASLOW:		;MASTER SEQUENCE NUMBER IS LOW
	LXI	H,MSEQ
	CALL	WRITESEQ;SEQUENCE NUMBER
MLOOP:	GET	MFILE
	PUSH	PSW	;SAVE MASTER CHARACTER
	PUT	NEW
	POP	PSW	;LF OR EOF?
	CPI	LF
	JZ	ENDMS
	CPI	EOF
	JZ	ENDMS
	JMP	MLOOP	;MORE TO COPY
;
ENDMS:	CALL	READM	;READ NEW SEQ NUMBER
	JMP	MERGE	;TO MERGE ANOTHER
;
ENDMERGE:
	;CLOSE ALL FILES FOR RENAMING
	FINIS	<UFILE,MFILE,NEW>
	;OLD MASTER FILE FOR ERASE/RENAME
	FILE	SETFILE,OLDMAS,,l,MBK
	ERASE	OLDMAS
	;RENAME	MASTER TO MBK
	RENAME	OLDMAS,MFILE
	;OLD UPDATE FILE FOR ERASE/RENAME
	FILE	SETFILE,OLDUPD,,l,UBK
	ERASE	OLDUPD
	;RENAME	UPDATE TO UBK
	RENAME	OLDUPD,UFILE
	;RENAME	NEW TO MASTER FILE
	RENAME	MFILE,NEW
	JMP 	BOOT
;
	DS	32	;16 LEVEL STACK
STACK:
;	BUFFER AREA
BUFFERS:
MEMSIZE	EQU	BUFFERS+@NXTB	;END OF MEMORY
	END
