	ORG	100H	;BEGINNING OF TPA
	MACLIB	SIMPIO	;SIMPLE READ/WRITE.
	MACLIB	NCOMPARE;COMPARISON OPS
	MACLIB	WHEN	;"WHEN" CONSTRUCT
	MACLIB	DOWHILE ;"DOWHILE" CONSTRUCT
	MACLIB	SELECT	;"SELECT" CONSTRUCT
;
;	USING THE CCP'S STACK, READ INPUT
;	CHARACTERS, UNTIL A Z IS TYPED
	WRITE <SAMPLE CONTROL STRUCTURES>
	WRITE <TYPE SINGLE CHARACTERS FROM>
	WRITE <A TO D, I^'^'LL STOP ON D>
;
	DOWHILE X,NEQ,%-D
	WRITE	<TYPE A CHARACTER: >
	READ X

	WHEN X,GEQ,%'A'
	  LDA X! ANI 05FH! STA X ;CONV CASE
	ENDW

	WHEN X,LSS,%'A'
	  MVI A,'E'! STA X ;SET TO ERROR
	ENDW

	WHEN X,GTR,%'E'
	  MVI A,'E'! STA X ;SET TO ERROR
	ENDW

	LDA X! SUI 'A' ;NORMALIZE TO 0-4
	  SELECT ;BASED ON X IN ACCUM
	    WRITE <YOU SELECTED CASE A>
	    SELNEXT
	    WRITE <YOU SELECTED CASE B>
	    SELNEXT
	    WRITE <YOU SELECTED CASE C>
	    SELNEXT
	    WRITE <YOU SELECTED CASE D>
	    WRITE <SO I"M GOING BACK^!>
	    SELNEXT
	    WRITE <BAD CHARACTER>
	  ENDSEL
	ENDDO
	RET		;BACK TO CCP
;	DATA	AREA
X:	DB	0		;X=00 INITIALLY

