	ORG	100H
	MACLIB	SEQIO	;SEQUENTAIL I/O LIB
;	PRINT THE X.PRN and X.SYM FILE ON THE
;	LINE PRINTER WITH PAGE FORMATTING.
;
FF	EQU	0CH	;FORM FEED
MAXLINE	EQU	56	;MAX LINES PER PAGE
;
;	SAVE THE ENTRY STACK POINTER
	LXI	H,0
	DAD	SP	;ENTRY SP TO HL
	SHLD	OLDSP	;SAVE ENTRY SP
	LXI	SP,STACK;SET TO LOCAL STACK
;
	FILE	INFILE,PRINT,,1,PRN,1000
;	READ THE PRINT FILE UNTIL END OF FILE
	CALL	EJECT
PRCYC:	GET	PRINT
	CPI	EOF
	JZ	ENDPR	;SKIP IF END FILE
	CALL	LISTING	;WRITE TO LISTING DEV
	JMP	PRCYC
ENDPR:	;END OF PRINT FILE, DELETE IT
	ERASE	PRINT
;
;	CHECK FOR THE OPTIONAL .SYM FILE
	FILE	SETFILE,SYMCHK,,1,SYM
	DIRECT	SYMCHK	;IS IT THERE?
	JZ	ENDLST	;SKIP SYMBOL IF SO
;
;	SYMBOL FILE IS PRESENT, PAGE EJECT
	CALL	EJECT
	FILE	INFILE,SYMBOL,,1,SYM,1000,PRINTBUF
;
SYCYCLE:
	GET	SYMBOL
	CPI	EOF
	JZ	ENDSY	;SKIP TO END OF EOF
	CALL	LISTING	;SEND TO PRINTER
	JMP	SYCYCLE	;FOR ANOTHER CHAR
;
ENDSY:	ERASE	SYMBOL	;ERASE .SYM FILE
;
ENDLST:	;END OF LISTING - EJECT AND RETURN
	CALL	EJECT
	LHLD	OLDSP	;ENTRY STACK POINTER
	SPHL	;RESTORE STACK POINTER
	RET	;TO CCP
;
;	UTILITY SUBROUTINES
LISTOUT:
	;SEND A SINGLE CHARACTER TO THE PRINTER
	PUT	LST
	LXI	H,CHARC	;CHARACTER COUNTER
	INR	M	;INCEMENT POSITION
	RET
;
LISTING:
	;WRITE CHARACTER FROM REG-A TO LIST DEVICE
	CPI	FF	;FORM-FEED?
	JNZ	LIST0
	XRA	A	;CLEAR LINE COUNT
	STA	LINEC
	STA	CHARC	;CLEAR TAB POSITION
	MVI	A,FF	;RETORE FORM FEED
LIST0:
	CPI	LF	;END OF LINE?
	JNZ	LIST1
	XRA	A	;CLEAR TAB POSITION
	STA	CHARC
	LXI	H,LINEC	;LINE COUNTER
	INR	M	;INCREMENT
	MOV	A,M	;CHECK FOR END OF PAGE
	CPI	MAXLINE	;LINE OVERFLOW?
	RC		;RETURN IF NOT
	MVI	M,0	;CLEAR LINEC
	MVI	A,FF	;SEND PAGE EJECT
LIST1:	CPI	TAB	;TAB CHARACTER?
	JNZ	LIST2
;	FEED BLANKS TO NEXT TAB POSITION
TABOUT:	MVI	A,' '
	CALL	LISTOUT
	LDA	CHARC	;CHARACTER POSITION
	ANI	7H	;MOD 8
	JNZ	TABOUT	;FOR ANOTHER BLANK
;	ON CHARACTER BOUNDARY
	RET
LIST2:	;SIMPLE CHARACTER
	JMP	LISTOUT	;PRINT AND RETURN
;
EJECT:	;PERFORM PAGE EJECT
	MVI	A,FF	;FORM FEED
	JMP	LISTOUT
;
;	DATA AREAS
	DS	64	;32 LEVEL STACK
STACK:
OLDSP:	DS	2	;ENTRY STACK POINTER
LINEC:	DS	1	;LINE COUNTER
CHARC:	DS	1	;CHARACTER COUNTER
;
BUFFERS:
	END

	
